package com.pucp.gestionlentesvr.dominio.actividad;

public enum TipoActividad {
    INICIO_SESION,
    CIERRE_SESION,
    REGISTRO_DISPOSITIVO,
    ACTUALIZACION_FIRMWARE,
    INSTALACION_APLICACION,
    DESINSTALACION_APLICACION,
    CONFIGURACION_DISPOSITIVO,
    CAMBIO_ESTADO_DISPOSITIVO,
    ASIGNACION_GRUPO,
    CREACION_USUARIO,
    MODIFICACION_USUARIO,
    CREACION_GRUPO,
    MODIFICACION_GRUPO
}
