//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontVR.ServiceReference4 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class aplicacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort activoField;
        
        private categoriaAplicacion categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private string desarrolladorField;
        
        private string descripcionField;
        
        private int idField;
        
        private string nombreField;
        
        private double tamanombField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public categoriaAplicacion categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified {
            get {
                return this.categoriaFieldSpecified;
            }
            set {
                this.categoriaFieldSpecified = value;
                this.RaisePropertyChanged("categoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string desarrollador {
            get {
                return this.desarrolladorField;
            }
            set {
                this.desarrolladorField = value;
                this.RaisePropertyChanged("desarrollador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double tamanomb {
            get {
                return this.tamanombField;
            }
            set {
                this.tamanombField = value;
                this.RaisePropertyChanged("tamanomb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public enum categoriaAplicacion {
        
        /// <remarks/>
        EDUCATIVA,
        
        /// <remarks/>
        ENTRETENIMIENTO,
        
        /// <remarks/>
        TERAPEUTICA,
        
        /// <remarks/>
        ENTRENAMIENTO,
        
        /// <remarks/>
        PRODUCTIVIDAD,
        
        /// <remarks/>
        SIMULACION,
        
        /// <remarks/>
        MULTIMEDIA,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", ConfigurationName="ServiceReference4.AplicacionWS")]
    public interface AplicacionWS {
        
        // CODEGEN: El parámetro 'elemento' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/actualizarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/actualizarAplicacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference4.Exception), Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/actualizarAplicacion/Fault/Except" +
            "ion", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.ServiceReference4.actualizarAplicacionResponse actualizarAplicacion(FrontVR.ServiceReference4.actualizarAplicacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/actualizarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/actualizarAplicacionResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.actualizarAplicacionResponse> actualizarAplicacionAsync(FrontVR.ServiceReference4.actualizarAplicacionRequest request);
        
        // CODEGEN: El parámetro 'elemento' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/registrarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/registrarAplicacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference4.Exception), Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/registrarAplicacion/Fault/Excepti" +
            "on", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.ServiceReference4.registrarAplicacionResponse registrarAplicacion(FrontVR.ServiceReference4.registrarAplicacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/registrarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/registrarAplicacionResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.registrarAplicacionResponse> registrarAplicacionAsync(FrontVR.ServiceReference4.registrarAplicacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/obtenerAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/obtenerAplicacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference4.Exception), Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/obtenerAplicacion/Fault/Exception" +
            "", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.ServiceReference4.obtenerAplicacionResponse obtenerAplicacion(FrontVR.ServiceReference4.obtenerAplicacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/obtenerAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/obtenerAplicacionResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.obtenerAplicacionResponse> obtenerAplicacionAsync(FrontVR.ServiceReference4.obtenerAplicacionRequest request);
        
        // CODEGEN: El parámetro 'id' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/eliminarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/eliminarAplicacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference4.Exception), Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/eliminarAplicacion/Fault/Exceptio" +
            "n", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.ServiceReference4.eliminarAplicacionResponse eliminarAplicacion(FrontVR.ServiceReference4.eliminarAplicacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/eliminarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/eliminarAplicacionResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.eliminarAplicacionResponse> eliminarAplicacionAsync(FrontVR.ServiceReference4.eliminarAplicacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarAplicacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference4.Exception), Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarAplicacion/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.ServiceReference4.listarAplicacionResponse listarAplicacion(FrontVR.ServiceReference4.listarAplicacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarAplicacionRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarAplicacionResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.listarAplicacionResponse> listarAplicacionAsync(FrontVR.ServiceReference4.listarAplicacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/eliminarAplicacionesPorDispositiv" +
            "oRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/eliminarAplicacionesPorDispositiv" +
            "oResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference4.Exception), Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/eliminarAplicacionesPorDispositiv" +
            "o/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarAplicacionesPorDispositivo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/eliminarAplicacionesPorDispositiv" +
            "oRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/eliminarAplicacionesPorDispositiv" +
            "oResponse")]
        System.Threading.Tasks.Task eliminarAplicacionesPorDispositivoAsync();
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarDispositivosPorAplicaciones" +
            "Request", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarDispositivosPorAplicaciones" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference4.Exception), Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarDispositivosPorAplicaciones" +
            "/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.ServiceReference4.listarDispositivosPorAplicacionesResponse listarDispositivosPorAplicaciones(FrontVR.ServiceReference4.listarDispositivosPorAplicacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarDispositivosPorAplicaciones" +
            "Request", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarDispositivosPorAplicaciones" +
            "Response")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.listarDispositivosPorAplicacionesResponse> listarDispositivosPorAplicacionesAsync(FrontVR.ServiceReference4.listarDispositivosPorAplicacionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarAplicacionesConDispositivos" +
            "Request", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarAplicacionesConDispositivos" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference4.Exception), Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarAplicacionesConDispositivos" +
            "/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.ServiceReference4.listarAplicacionesConDispositivosResponse listarAplicacionesConDispositivos(FrontVR.ServiceReference4.listarAplicacionesConDispositivosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarAplicacionesConDispositivos" +
            "Request", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/listarAplicacionesConDispositivos" +
            "Response")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.listarAplicacionesConDispositivosResponse> listarAplicacionesConDispositivosAsync(FrontVR.ServiceReference4.listarAplicacionesConDispositivosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/contarAplicacionesPorTipoEnMetric" +
            "asRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/contarAplicacionesPorTipoEnMetric" +
            "asResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference4.Exception), Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/contarAplicacionesPorTipoEnMetric" +
            "as/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.ServiceReference4.contarAplicacionesPorTipoEnMetricasResponse contarAplicacionesPorTipoEnMetricas(FrontVR.ServiceReference4.contarAplicacionesPorTipoEnMetricasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/AplicacionWS/contarAplicacionesPorTipoEnMetric" +
            "asRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/AplicacionWS/contarAplicacionesPorTipoEnMetric" +
            "asResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.contarAplicacionesPorTipoEnMetricasResponse> contarAplicacionesPorTipoEnMetricasAsync(FrontVR.ServiceReference4.contarAplicacionesPorTipoEnMetricasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarAplicacion", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class actualizarAplicacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference4.aplicacion elemento;
        
        public actualizarAplicacionRequest() {
        }
        
        public actualizarAplicacionRequest(FrontVR.ServiceReference4.aplicacion elemento) {
            this.elemento = elemento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarAplicacionResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class actualizarAplicacionResponse {
        
        public actualizarAplicacionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarAplicacion", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class registrarAplicacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference4.aplicacion elemento;
        
        public registrarAplicacionRequest() {
        }
        
        public registrarAplicacionRequest(FrontVR.ServiceReference4.aplicacion elemento) {
            this.elemento = elemento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarAplicacionResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class registrarAplicacionResponse {
        
        public registrarAplicacionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAplicacion", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerAplicacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerAplicacionRequest() {
        }
        
        public obtenerAplicacionRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAplicacionResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerAplicacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference4.aplicacion @return;
        
        public obtenerAplicacionResponse() {
        }
        
        public obtenerAplicacionResponse(FrontVR.ServiceReference4.aplicacion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAplicacion", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class eliminarAplicacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarAplicacionRequest() {
        }
        
        public eliminarAplicacionRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAplicacionResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class eliminarAplicacionResponse {
        
        public eliminarAplicacionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAplicacion", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class listarAplicacionRequest {
        
        public listarAplicacionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAplicacionResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class listarAplicacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference4.aplicacion[] @return;
        
        public listarAplicacionResponse() {
        }
        
        public listarAplicacionResponse(FrontVR.ServiceReference4.aplicacion[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class dispositivo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort activoField;
        
        private estadoConexion estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private grupo grupoField;
        
        private int idField;
        
        private string modeloField;
        
        private int nivelBateriaField;
        
        private string nombreField;
        
        private string numeroSerieField;
        
        private string ubicacionField;
        
        private System.DateTime ultimaConexionField;
        
        private bool ultimaConexionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoConexion estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public grupo grupo {
            get {
                return this.grupoField;
            }
            set {
                this.grupoField = value;
                this.RaisePropertyChanged("grupo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int nivelBateria {
            get {
                return this.nivelBateriaField;
            }
            set {
                this.nivelBateriaField = value;
                this.RaisePropertyChanged("nivelBateria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string numeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                this.numeroSerieField = value;
                this.RaisePropertyChanged("numeroSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime ultimaConexion {
            get {
                return this.ultimaConexionField;
            }
            set {
                this.ultimaConexionField = value;
                this.RaisePropertyChanged("ultimaConexion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ultimaConexionSpecified {
            get {
                return this.ultimaConexionFieldSpecified;
            }
            set {
                this.ultimaConexionFieldSpecified = value;
                this.RaisePropertyChanged("ultimaConexionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public enum estadoConexion {
        
        /// <remarks/>
        CONECTADO,
        
        /// <remarks/>
        DESCONECTADO,
        
        /// <remarks/>
        EN_USO,
        
        /// <remarks/>
        EN_MANTENIMIENTO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class grupo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort activoField;
        
        private string descripcionField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private int idField;
        
        private string nombreField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDispositivosPorAplicaciones", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class listarDispositivosPorAplicacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public listarDispositivosPorAplicacionesRequest() {
        }
        
        public listarDispositivosPorAplicacionesRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDispositivosPorAplicacionesResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class listarDispositivosPorAplicacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference4.dispositivo[] @return;
        
        public listarDispositivosPorAplicacionesResponse() {
        }
        
        public listarDispositivosPorAplicacionesResponse(FrontVR.ServiceReference4.dispositivo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAplicacionesConDispositivos", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class listarAplicacionesConDispositivosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public listarAplicacionesConDispositivosRequest() {
        }
        
        public listarAplicacionesConDispositivosRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAplicacionesConDispositivosResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class listarAplicacionesConDispositivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference4.aplicacion[] @return;
        
        public listarAplicacionesConDispositivosResponse() {
        }
        
        public listarAplicacionesConDispositivosResponse(FrontVR.ServiceReference4.aplicacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarAplicacionesPorTipoEnMetricas", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class contarAplicacionesPorTipoEnMetricasRequest {
        
        public contarAplicacionesPorTipoEnMetricasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarAplicacionesPorTipoEnMetricasResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class contarAplicacionesPorTipoEnMetricasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] @return;
        
        public contarAplicacionesPorTipoEnMetricasResponse() {
        }
        
        public contarAplicacionesPorTipoEnMetricasResponse(int[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AplicacionWSChannel : FrontVR.ServiceReference4.AplicacionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AplicacionWSClient : System.ServiceModel.ClientBase<FrontVR.ServiceReference4.AplicacionWS>, FrontVR.ServiceReference4.AplicacionWS {
        
        public AplicacionWSClient() {
        }
        
        public AplicacionWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AplicacionWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AplicacionWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AplicacionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference4.actualizarAplicacionResponse FrontVR.ServiceReference4.AplicacionWS.actualizarAplicacion(FrontVR.ServiceReference4.actualizarAplicacionRequest request) {
            return base.Channel.actualizarAplicacion(request);
        }
        
        public void actualizarAplicacion(FrontVR.ServiceReference4.aplicacion elemento) {
            FrontVR.ServiceReference4.actualizarAplicacionRequest inValue = new FrontVR.ServiceReference4.actualizarAplicacionRequest();
            inValue.elemento = elemento;
            FrontVR.ServiceReference4.actualizarAplicacionResponse retVal = ((FrontVR.ServiceReference4.AplicacionWS)(this)).actualizarAplicacion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.actualizarAplicacionResponse> FrontVR.ServiceReference4.AplicacionWS.actualizarAplicacionAsync(FrontVR.ServiceReference4.actualizarAplicacionRequest request) {
            return base.Channel.actualizarAplicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference4.actualizarAplicacionResponse> actualizarAplicacionAsync(FrontVR.ServiceReference4.aplicacion elemento) {
            FrontVR.ServiceReference4.actualizarAplicacionRequest inValue = new FrontVR.ServiceReference4.actualizarAplicacionRequest();
            inValue.elemento = elemento;
            return ((FrontVR.ServiceReference4.AplicacionWS)(this)).actualizarAplicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference4.registrarAplicacionResponse FrontVR.ServiceReference4.AplicacionWS.registrarAplicacion(FrontVR.ServiceReference4.registrarAplicacionRequest request) {
            return base.Channel.registrarAplicacion(request);
        }
        
        public void registrarAplicacion(FrontVR.ServiceReference4.aplicacion elemento) {
            FrontVR.ServiceReference4.registrarAplicacionRequest inValue = new FrontVR.ServiceReference4.registrarAplicacionRequest();
            inValue.elemento = elemento;
            FrontVR.ServiceReference4.registrarAplicacionResponse retVal = ((FrontVR.ServiceReference4.AplicacionWS)(this)).registrarAplicacion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.registrarAplicacionResponse> FrontVR.ServiceReference4.AplicacionWS.registrarAplicacionAsync(FrontVR.ServiceReference4.registrarAplicacionRequest request) {
            return base.Channel.registrarAplicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference4.registrarAplicacionResponse> registrarAplicacionAsync(FrontVR.ServiceReference4.aplicacion elemento) {
            FrontVR.ServiceReference4.registrarAplicacionRequest inValue = new FrontVR.ServiceReference4.registrarAplicacionRequest();
            inValue.elemento = elemento;
            return ((FrontVR.ServiceReference4.AplicacionWS)(this)).registrarAplicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference4.obtenerAplicacionResponse FrontVR.ServiceReference4.AplicacionWS.obtenerAplicacion(FrontVR.ServiceReference4.obtenerAplicacionRequest request) {
            return base.Channel.obtenerAplicacion(request);
        }
        
        public FrontVR.ServiceReference4.aplicacion obtenerAplicacion(int id) {
            FrontVR.ServiceReference4.obtenerAplicacionRequest inValue = new FrontVR.ServiceReference4.obtenerAplicacionRequest();
            inValue.id = id;
            FrontVR.ServiceReference4.obtenerAplicacionResponse retVal = ((FrontVR.ServiceReference4.AplicacionWS)(this)).obtenerAplicacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.obtenerAplicacionResponse> FrontVR.ServiceReference4.AplicacionWS.obtenerAplicacionAsync(FrontVR.ServiceReference4.obtenerAplicacionRequest request) {
            return base.Channel.obtenerAplicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference4.obtenerAplicacionResponse> obtenerAplicacionAsync(int id) {
            FrontVR.ServiceReference4.obtenerAplicacionRequest inValue = new FrontVR.ServiceReference4.obtenerAplicacionRequest();
            inValue.id = id;
            return ((FrontVR.ServiceReference4.AplicacionWS)(this)).obtenerAplicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference4.eliminarAplicacionResponse FrontVR.ServiceReference4.AplicacionWS.eliminarAplicacion(FrontVR.ServiceReference4.eliminarAplicacionRequest request) {
            return base.Channel.eliminarAplicacion(request);
        }
        
        public void eliminarAplicacion(int id) {
            FrontVR.ServiceReference4.eliminarAplicacionRequest inValue = new FrontVR.ServiceReference4.eliminarAplicacionRequest();
            inValue.id = id;
            FrontVR.ServiceReference4.eliminarAplicacionResponse retVal = ((FrontVR.ServiceReference4.AplicacionWS)(this)).eliminarAplicacion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.eliminarAplicacionResponse> FrontVR.ServiceReference4.AplicacionWS.eliminarAplicacionAsync(FrontVR.ServiceReference4.eliminarAplicacionRequest request) {
            return base.Channel.eliminarAplicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference4.eliminarAplicacionResponse> eliminarAplicacionAsync(int id) {
            FrontVR.ServiceReference4.eliminarAplicacionRequest inValue = new FrontVR.ServiceReference4.eliminarAplicacionRequest();
            inValue.id = id;
            return ((FrontVR.ServiceReference4.AplicacionWS)(this)).eliminarAplicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference4.listarAplicacionResponse FrontVR.ServiceReference4.AplicacionWS.listarAplicacion(FrontVR.ServiceReference4.listarAplicacionRequest request) {
            return base.Channel.listarAplicacion(request);
        }
        
        public FrontVR.ServiceReference4.aplicacion[] listarAplicacion() {
            FrontVR.ServiceReference4.listarAplicacionRequest inValue = new FrontVR.ServiceReference4.listarAplicacionRequest();
            FrontVR.ServiceReference4.listarAplicacionResponse retVal = ((FrontVR.ServiceReference4.AplicacionWS)(this)).listarAplicacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.listarAplicacionResponse> FrontVR.ServiceReference4.AplicacionWS.listarAplicacionAsync(FrontVR.ServiceReference4.listarAplicacionRequest request) {
            return base.Channel.listarAplicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference4.listarAplicacionResponse> listarAplicacionAsync() {
            FrontVR.ServiceReference4.listarAplicacionRequest inValue = new FrontVR.ServiceReference4.listarAplicacionRequest();
            return ((FrontVR.ServiceReference4.AplicacionWS)(this)).listarAplicacionAsync(inValue);
        }
        
        public void eliminarAplicacionesPorDispositivo() {
            base.Channel.eliminarAplicacionesPorDispositivo();
        }
        
        public System.Threading.Tasks.Task eliminarAplicacionesPorDispositivoAsync() {
            return base.Channel.eliminarAplicacionesPorDispositivoAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference4.listarDispositivosPorAplicacionesResponse FrontVR.ServiceReference4.AplicacionWS.listarDispositivosPorAplicaciones(FrontVR.ServiceReference4.listarDispositivosPorAplicacionesRequest request) {
            return base.Channel.listarDispositivosPorAplicaciones(request);
        }
        
        public FrontVR.ServiceReference4.dispositivo[] listarDispositivosPorAplicaciones(int id) {
            FrontVR.ServiceReference4.listarDispositivosPorAplicacionesRequest inValue = new FrontVR.ServiceReference4.listarDispositivosPorAplicacionesRequest();
            inValue.id = id;
            FrontVR.ServiceReference4.listarDispositivosPorAplicacionesResponse retVal = ((FrontVR.ServiceReference4.AplicacionWS)(this)).listarDispositivosPorAplicaciones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.listarDispositivosPorAplicacionesResponse> FrontVR.ServiceReference4.AplicacionWS.listarDispositivosPorAplicacionesAsync(FrontVR.ServiceReference4.listarDispositivosPorAplicacionesRequest request) {
            return base.Channel.listarDispositivosPorAplicacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference4.listarDispositivosPorAplicacionesResponse> listarDispositivosPorAplicacionesAsync(int id) {
            FrontVR.ServiceReference4.listarDispositivosPorAplicacionesRequest inValue = new FrontVR.ServiceReference4.listarDispositivosPorAplicacionesRequest();
            inValue.id = id;
            return ((FrontVR.ServiceReference4.AplicacionWS)(this)).listarDispositivosPorAplicacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference4.listarAplicacionesConDispositivosResponse FrontVR.ServiceReference4.AplicacionWS.listarAplicacionesConDispositivos(FrontVR.ServiceReference4.listarAplicacionesConDispositivosRequest request) {
            return base.Channel.listarAplicacionesConDispositivos(request);
        }
        
        public FrontVR.ServiceReference4.aplicacion[] listarAplicacionesConDispositivos(int id) {
            FrontVR.ServiceReference4.listarAplicacionesConDispositivosRequest inValue = new FrontVR.ServiceReference4.listarAplicacionesConDispositivosRequest();
            inValue.id = id;
            FrontVR.ServiceReference4.listarAplicacionesConDispositivosResponse retVal = ((FrontVR.ServiceReference4.AplicacionWS)(this)).listarAplicacionesConDispositivos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.listarAplicacionesConDispositivosResponse> FrontVR.ServiceReference4.AplicacionWS.listarAplicacionesConDispositivosAsync(FrontVR.ServiceReference4.listarAplicacionesConDispositivosRequest request) {
            return base.Channel.listarAplicacionesConDispositivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference4.listarAplicacionesConDispositivosResponse> listarAplicacionesConDispositivosAsync(int id) {
            FrontVR.ServiceReference4.listarAplicacionesConDispositivosRequest inValue = new FrontVR.ServiceReference4.listarAplicacionesConDispositivosRequest();
            inValue.id = id;
            return ((FrontVR.ServiceReference4.AplicacionWS)(this)).listarAplicacionesConDispositivosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference4.contarAplicacionesPorTipoEnMetricasResponse FrontVR.ServiceReference4.AplicacionWS.contarAplicacionesPorTipoEnMetricas(FrontVR.ServiceReference4.contarAplicacionesPorTipoEnMetricasRequest request) {
            return base.Channel.contarAplicacionesPorTipoEnMetricas(request);
        }
        
        public int[] contarAplicacionesPorTipoEnMetricas() {
            FrontVR.ServiceReference4.contarAplicacionesPorTipoEnMetricasRequest inValue = new FrontVR.ServiceReference4.contarAplicacionesPorTipoEnMetricasRequest();
            FrontVR.ServiceReference4.contarAplicacionesPorTipoEnMetricasResponse retVal = ((FrontVR.ServiceReference4.AplicacionWS)(this)).contarAplicacionesPorTipoEnMetricas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference4.contarAplicacionesPorTipoEnMetricasResponse> FrontVR.ServiceReference4.AplicacionWS.contarAplicacionesPorTipoEnMetricasAsync(FrontVR.ServiceReference4.contarAplicacionesPorTipoEnMetricasRequest request) {
            return base.Channel.contarAplicacionesPorTipoEnMetricasAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference4.contarAplicacionesPorTipoEnMetricasResponse> contarAplicacionesPorTipoEnMetricasAsync() {
            FrontVR.ServiceReference4.contarAplicacionesPorTipoEnMetricasRequest inValue = new FrontVR.ServiceReference4.contarAplicacionesPorTipoEnMetricasRequest();
            return ((FrontVR.ServiceReference4.AplicacionWS)(this)).contarAplicacionesPorTipoEnMetricasAsync(inValue);
        }
    }
}
