//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontVR.DispositivoWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.pucp.gestionlentesvr")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.pucp.gestionlentesvr")]
    public partial class grupo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort activoField;
        
        private string descripcionField;
        
        private date fechaCreacionField;
        
        private int idField;
        
        private string nombreField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public date fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.pucp.gestionlentesvr")]
    public partial class date : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.pucp.gestionlentesvr")]
    public partial class dispositivo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort activoField;
        
        private estadoConexion estadoField;
        
        private bool estadoFieldSpecified;
        
        private date fechaRegistroField;
        
        private grupo grupoField;
        
        private int idField;
        
        private string modeloField;
        
        private int nivelBateriaField;
        
        private string nombreField;
        
        private string numeroSerieField;
        
        private string ubicacionField;
        
        private date ultimaConexionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoConexion estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public date fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public grupo grupo {
            get {
                return this.grupoField;
            }
            set {
                this.grupoField = value;
                this.RaisePropertyChanged("grupo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int nivelBateria {
            get {
                return this.nivelBateriaField;
            }
            set {
                this.nivelBateriaField = value;
                this.RaisePropertyChanged("nivelBateria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string numeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                this.numeroSerieField = value;
                this.RaisePropertyChanged("numeroSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public date ultimaConexion {
            get {
                return this.ultimaConexionField;
            }
            set {
                this.ultimaConexionField = value;
                this.RaisePropertyChanged("ultimaConexion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.pucp.gestionlentesvr")]
    public enum estadoConexion {
        
        /// <remarks/>
        CONECTADO,
        
        /// <remarks/>
        DESCONECTADO,
        
        /// <remarks/>
        EN_USO,
        
        /// <remarks/>
        EN_MANTENIMIENTO,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="com.pucp.gestionlentesvr", ConfigurationName="DispositivoWS.DispositivoWS")]
    public interface DispositivoWS {
        
        // CODEGEN: El parámetro 'elemento' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="com.pucp.gestionlentesvr/DispositivoWS/actualizarDispositivoRequest", ReplyAction="com.pucp.gestionlentesvr/DispositivoWS/actualizarDispositivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.DispositivoWS.Exception), Action="com.pucp.gestionlentesvr/DispositivoWS/actualizarDispositivo/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.DispositivoWS.actualizarDispositivoResponse actualizarDispositivo(FrontVR.DispositivoWS.actualizarDispositivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.pucp.gestionlentesvr/DispositivoWS/actualizarDispositivoRequest", ReplyAction="com.pucp.gestionlentesvr/DispositivoWS/actualizarDispositivoResponse")]
        System.Threading.Tasks.Task<FrontVR.DispositivoWS.actualizarDispositivoResponse> actualizarDispositivoAsync(FrontVR.DispositivoWS.actualizarDispositivoRequest request);
        
        // CODEGEN: El parámetro 'id' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="com.pucp.gestionlentesvr/DispositivoWS/eliminarDispositivoRequest", ReplyAction="com.pucp.gestionlentesvr/DispositivoWS/eliminarDispositivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.DispositivoWS.Exception), Action="com.pucp.gestionlentesvr/DispositivoWS/eliminarDispositivo/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.DispositivoWS.eliminarDispositivoResponse eliminarDispositivo(FrontVR.DispositivoWS.eliminarDispositivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.pucp.gestionlentesvr/DispositivoWS/eliminarDispositivoRequest", ReplyAction="com.pucp.gestionlentesvr/DispositivoWS/eliminarDispositivoResponse")]
        System.Threading.Tasks.Task<FrontVR.DispositivoWS.eliminarDispositivoResponse> eliminarDispositivoAsync(FrontVR.DispositivoWS.eliminarDispositivoRequest request);
        
        // CODEGEN: El parámetro 'elemento' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="com.pucp.gestionlentesvr/DispositivoWS/registrarDispositivoRequest", ReplyAction="com.pucp.gestionlentesvr/DispositivoWS/registrarDispositivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.DispositivoWS.Exception), Action="com.pucp.gestionlentesvr/DispositivoWS/registrarDispositivo/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.DispositivoWS.registrarDispositivoResponse registrarDispositivo(FrontVR.DispositivoWS.registrarDispositivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.pucp.gestionlentesvr/DispositivoWS/registrarDispositivoRequest", ReplyAction="com.pucp.gestionlentesvr/DispositivoWS/registrarDispositivoResponse")]
        System.Threading.Tasks.Task<FrontVR.DispositivoWS.registrarDispositivoResponse> registrarDispositivoAsync(FrontVR.DispositivoWS.registrarDispositivoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="com.pucp.gestionlentesvr/DispositivoWS/listarDispositivoRequest", ReplyAction="com.pucp.gestionlentesvr/DispositivoWS/listarDispositivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.DispositivoWS.Exception), Action="com.pucp.gestionlentesvr/DispositivoWS/listarDispositivo/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.DispositivoWS.listarDispositivoResponse listarDispositivo(FrontVR.DispositivoWS.listarDispositivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.pucp.gestionlentesvr/DispositivoWS/listarDispositivoRequest", ReplyAction="com.pucp.gestionlentesvr/DispositivoWS/listarDispositivoResponse")]
        System.Threading.Tasks.Task<FrontVR.DispositivoWS.listarDispositivoResponse> listarDispositivoAsync(FrontVR.DispositivoWS.listarDispositivoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="com.pucp.gestionlentesvr/DispositivoWS/obtenerDispositivoRequest", ReplyAction="com.pucp.gestionlentesvr/DispositivoWS/obtenerDispositivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.DispositivoWS.Exception), Action="com.pucp.gestionlentesvr/DispositivoWS/obtenerDispositivo/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.DispositivoWS.obtenerDispositivoResponse obtenerDispositivo(FrontVR.DispositivoWS.obtenerDispositivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.pucp.gestionlentesvr/DispositivoWS/obtenerDispositivoRequest", ReplyAction="com.pucp.gestionlentesvr/DispositivoWS/obtenerDispositivoResponse")]
        System.Threading.Tasks.Task<FrontVR.DispositivoWS.obtenerDispositivoResponse> obtenerDispositivoAsync(FrontVR.DispositivoWS.obtenerDispositivoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarDispositivo", WrapperNamespace="com.pucp.gestionlentesvr", IsWrapped=true)]
    public partial class actualizarDispositivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.pucp.gestionlentesvr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.DispositivoWS.dispositivo elemento;
        
        public actualizarDispositivoRequest() {
        }
        
        public actualizarDispositivoRequest(FrontVR.DispositivoWS.dispositivo elemento) {
            this.elemento = elemento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarDispositivoResponse", WrapperNamespace="com.pucp.gestionlentesvr", IsWrapped=true)]
    public partial class actualizarDispositivoResponse {
        
        public actualizarDispositivoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDispositivo", WrapperNamespace="com.pucp.gestionlentesvr", IsWrapped=true)]
    public partial class eliminarDispositivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.pucp.gestionlentesvr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarDispositivoRequest() {
        }
        
        public eliminarDispositivoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDispositivoResponse", WrapperNamespace="com.pucp.gestionlentesvr", IsWrapped=true)]
    public partial class eliminarDispositivoResponse {
        
        public eliminarDispositivoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarDispositivo", WrapperNamespace="com.pucp.gestionlentesvr", IsWrapped=true)]
    public partial class registrarDispositivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.pucp.gestionlentesvr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.DispositivoWS.dispositivo elemento;
        
        public registrarDispositivoRequest() {
        }
        
        public registrarDispositivoRequest(FrontVR.DispositivoWS.dispositivo elemento) {
            this.elemento = elemento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarDispositivoResponse", WrapperNamespace="com.pucp.gestionlentesvr", IsWrapped=true)]
    public partial class registrarDispositivoResponse {
        
        public registrarDispositivoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDispositivo", WrapperNamespace="com.pucp.gestionlentesvr", IsWrapped=true)]
    public partial class listarDispositivoRequest {
        
        public listarDispositivoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDispositivoResponse", WrapperNamespace="com.pucp.gestionlentesvr", IsWrapped=true)]
    public partial class listarDispositivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.pucp.gestionlentesvr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.DispositivoWS.dispositivo[] @return;
        
        public listarDispositivoResponse() {
        }
        
        public listarDispositivoResponse(FrontVR.DispositivoWS.dispositivo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDispositivo", WrapperNamespace="com.pucp.gestionlentesvr", IsWrapped=true)]
    public partial class obtenerDispositivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.pucp.gestionlentesvr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerDispositivoRequest() {
        }
        
        public obtenerDispositivoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDispositivoResponse", WrapperNamespace="com.pucp.gestionlentesvr", IsWrapped=true)]
    public partial class obtenerDispositivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.pucp.gestionlentesvr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.DispositivoWS.dispositivo @return;
        
        public obtenerDispositivoResponse() {
        }
        
        public obtenerDispositivoResponse(FrontVR.DispositivoWS.dispositivo @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DispositivoWSChannel : FrontVR.DispositivoWS.DispositivoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DispositivoWSClient : System.ServiceModel.ClientBase<FrontVR.DispositivoWS.DispositivoWS>, FrontVR.DispositivoWS.DispositivoWS {
        
        public DispositivoWSClient() {
        }
        
        public DispositivoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DispositivoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DispositivoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DispositivoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.DispositivoWS.actualizarDispositivoResponse FrontVR.DispositivoWS.DispositivoWS.actualizarDispositivo(FrontVR.DispositivoWS.actualizarDispositivoRequest request) {
            return base.Channel.actualizarDispositivo(request);
        }
        
        public void actualizarDispositivo(FrontVR.DispositivoWS.dispositivo elemento) {
            FrontVR.DispositivoWS.actualizarDispositivoRequest inValue = new FrontVR.DispositivoWS.actualizarDispositivoRequest();
            inValue.elemento = elemento;
            FrontVR.DispositivoWS.actualizarDispositivoResponse retVal = ((FrontVR.DispositivoWS.DispositivoWS)(this)).actualizarDispositivo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.DispositivoWS.actualizarDispositivoResponse> FrontVR.DispositivoWS.DispositivoWS.actualizarDispositivoAsync(FrontVR.DispositivoWS.actualizarDispositivoRequest request) {
            return base.Channel.actualizarDispositivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.DispositivoWS.actualizarDispositivoResponse> actualizarDispositivoAsync(FrontVR.DispositivoWS.dispositivo elemento) {
            FrontVR.DispositivoWS.actualizarDispositivoRequest inValue = new FrontVR.DispositivoWS.actualizarDispositivoRequest();
            inValue.elemento = elemento;
            return ((FrontVR.DispositivoWS.DispositivoWS)(this)).actualizarDispositivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.DispositivoWS.eliminarDispositivoResponse FrontVR.DispositivoWS.DispositivoWS.eliminarDispositivo(FrontVR.DispositivoWS.eliminarDispositivoRequest request) {
            return base.Channel.eliminarDispositivo(request);
        }
        
        public void eliminarDispositivo(int id) {
            FrontVR.DispositivoWS.eliminarDispositivoRequest inValue = new FrontVR.DispositivoWS.eliminarDispositivoRequest();
            inValue.id = id;
            FrontVR.DispositivoWS.eliminarDispositivoResponse retVal = ((FrontVR.DispositivoWS.DispositivoWS)(this)).eliminarDispositivo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.DispositivoWS.eliminarDispositivoResponse> FrontVR.DispositivoWS.DispositivoWS.eliminarDispositivoAsync(FrontVR.DispositivoWS.eliminarDispositivoRequest request) {
            return base.Channel.eliminarDispositivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.DispositivoWS.eliminarDispositivoResponse> eliminarDispositivoAsync(int id) {
            FrontVR.DispositivoWS.eliminarDispositivoRequest inValue = new FrontVR.DispositivoWS.eliminarDispositivoRequest();
            inValue.id = id;
            return ((FrontVR.DispositivoWS.DispositivoWS)(this)).eliminarDispositivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.DispositivoWS.registrarDispositivoResponse FrontVR.DispositivoWS.DispositivoWS.registrarDispositivo(FrontVR.DispositivoWS.registrarDispositivoRequest request) {
            return base.Channel.registrarDispositivo(request);
        }
        
        public void registrarDispositivo(FrontVR.DispositivoWS.dispositivo elemento) {
            FrontVR.DispositivoWS.registrarDispositivoRequest inValue = new FrontVR.DispositivoWS.registrarDispositivoRequest();
            inValue.elemento = elemento;
            FrontVR.DispositivoWS.registrarDispositivoResponse retVal = ((FrontVR.DispositivoWS.DispositivoWS)(this)).registrarDispositivo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.DispositivoWS.registrarDispositivoResponse> FrontVR.DispositivoWS.DispositivoWS.registrarDispositivoAsync(FrontVR.DispositivoWS.registrarDispositivoRequest request) {
            return base.Channel.registrarDispositivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.DispositivoWS.registrarDispositivoResponse> registrarDispositivoAsync(FrontVR.DispositivoWS.dispositivo elemento) {
            FrontVR.DispositivoWS.registrarDispositivoRequest inValue = new FrontVR.DispositivoWS.registrarDispositivoRequest();
            inValue.elemento = elemento;
            return ((FrontVR.DispositivoWS.DispositivoWS)(this)).registrarDispositivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.DispositivoWS.listarDispositivoResponse FrontVR.DispositivoWS.DispositivoWS.listarDispositivo(FrontVR.DispositivoWS.listarDispositivoRequest request) {
            return base.Channel.listarDispositivo(request);
        }
        
        public FrontVR.DispositivoWS.dispositivo[] listarDispositivo() {
            FrontVR.DispositivoWS.listarDispositivoRequest inValue = new FrontVR.DispositivoWS.listarDispositivoRequest();
            FrontVR.DispositivoWS.listarDispositivoResponse retVal = ((FrontVR.DispositivoWS.DispositivoWS)(this)).listarDispositivo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.DispositivoWS.listarDispositivoResponse> FrontVR.DispositivoWS.DispositivoWS.listarDispositivoAsync(FrontVR.DispositivoWS.listarDispositivoRequest request) {
            return base.Channel.listarDispositivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.DispositivoWS.listarDispositivoResponse> listarDispositivoAsync() {
            FrontVR.DispositivoWS.listarDispositivoRequest inValue = new FrontVR.DispositivoWS.listarDispositivoRequest();
            return ((FrontVR.DispositivoWS.DispositivoWS)(this)).listarDispositivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.DispositivoWS.obtenerDispositivoResponse FrontVR.DispositivoWS.DispositivoWS.obtenerDispositivo(FrontVR.DispositivoWS.obtenerDispositivoRequest request) {
            return base.Channel.obtenerDispositivo(request);
        }
        
        public FrontVR.DispositivoWS.dispositivo obtenerDispositivo(int id) {
            FrontVR.DispositivoWS.obtenerDispositivoRequest inValue = new FrontVR.DispositivoWS.obtenerDispositivoRequest();
            inValue.id = id;
            FrontVR.DispositivoWS.obtenerDispositivoResponse retVal = ((FrontVR.DispositivoWS.DispositivoWS)(this)).obtenerDispositivo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.DispositivoWS.obtenerDispositivoResponse> FrontVR.DispositivoWS.DispositivoWS.obtenerDispositivoAsync(FrontVR.DispositivoWS.obtenerDispositivoRequest request) {
            return base.Channel.obtenerDispositivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.DispositivoWS.obtenerDispositivoResponse> obtenerDispositivoAsync(int id) {
            FrontVR.DispositivoWS.obtenerDispositivoRequest inValue = new FrontVR.DispositivoWS.obtenerDispositivoRequest();
            inValue.id = id;
            return ((FrontVR.DispositivoWS.DispositivoWS)(this)).obtenerDispositivoAsync(inValue);
        }
    }
}
