//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontVR.ServiceReference2 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class rol : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort activoField;
        
        private string descripcionField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort activoField;
        
        private string apellidoField;
        
        private string contrasenaField;
        
        private string correoField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private int idField;
        
        private string nombreField;
        
        private rol rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public rol rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class grupo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort activoField;
        
        private string descripcionField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private int idField;
        
        private string nombreField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class dispositivo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort activoField;
        
        private estadoConexion estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private grupo grupoField;
        
        private int idField;
        
        private string modeloField;
        
        private int nivelBateriaField;
        
        private string nombreField;
        
        private string numeroSerieField;
        
        private string ubicacionField;
        
        private System.DateTime ultimaConexionField;
        
        private bool ultimaConexionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoConexion estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public grupo grupo {
            get {
                return this.grupoField;
            }
            set {
                this.grupoField = value;
                this.RaisePropertyChanged("grupo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int nivelBateria {
            get {
                return this.nivelBateriaField;
            }
            set {
                this.nivelBateriaField = value;
                this.RaisePropertyChanged("nivelBateria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string numeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                this.numeroSerieField = value;
                this.RaisePropertyChanged("numeroSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime ultimaConexion {
            get {
                return this.ultimaConexionField;
            }
            set {
                this.ultimaConexionField = value;
                this.RaisePropertyChanged("ultimaConexion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ultimaConexionSpecified {
            get {
                return this.ultimaConexionFieldSpecified;
            }
            set {
                this.ultimaConexionFieldSpecified = value;
                this.RaisePropertyChanged("ultimaConexionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public enum estadoConexion {
        
        /// <remarks/>
        CONECTADO,
        
        /// <remarks/>
        DESCONECTADO,
        
        /// <remarks/>
        EN_USO,
        
        /// <remarks/>
        EN_MANTENIMIENTO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class metricaUso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort activoField;
        
        private dispositivo dispositivoField;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private int idField;
        
        private int nivelBateriaFinalField;
        
        private int nivelBateriaInicialField;
        
        private int tiempoUsoMinutosField;
        
        private usuario usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public dispositivo dispositivo {
            get {
                return this.dispositivoField;
            }
            set {
                this.dispositivoField = value;
                this.RaisePropertyChanged("dispositivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int nivelBateriaFinal {
            get {
                return this.nivelBateriaFinalField;
            }
            set {
                this.nivelBateriaFinalField = value;
                this.RaisePropertyChanged("nivelBateriaFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int nivelBateriaInicial {
            get {
                return this.nivelBateriaInicialField;
            }
            set {
                this.nivelBateriaInicialField = value;
                this.RaisePropertyChanged("nivelBateriaInicial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int tiempoUsoMinutos {
            get {
                return this.tiempoUsoMinutosField;
            }
            set {
                this.tiempoUsoMinutosField = value;
                this.RaisePropertyChanged("tiempoUsoMinutos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", ConfigurationName="ServiceReference2.MetricaUsoWS")]
    public interface MetricaUsoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/listarMetricaUsoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/listarMetricaUsoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference2.Exception), Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/listarMetricaUso/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.ServiceReference2.listarMetricaUsoResponse listarMetricaUso(FrontVR.ServiceReference2.listarMetricaUsoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/listarMetricaUsoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/listarMetricaUsoResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.listarMetricaUsoResponse> listarMetricaUsoAsync(FrontVR.ServiceReference2.listarMetricaUsoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerAppMasUsadaRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerAppMasUsadaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference2.Exception), Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerAppMasUsada/Fault/Exceptio" +
            "n", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.ServiceReference2.obtenerAppMasUsadaResponse obtenerAppMasUsada(FrontVR.ServiceReference2.obtenerAppMasUsadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerAppMasUsadaRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerAppMasUsadaResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.obtenerAppMasUsadaResponse> obtenerAppMasUsadaAsync(FrontVR.ServiceReference2.obtenerAppMasUsadaRequest request);
        
        // CODEGEN: El parámetro 'id' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/eliminarMetricaUsoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/eliminarMetricaUsoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference2.Exception), Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/eliminarMetricaUso/Fault/Exceptio" +
            "n", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.ServiceReference2.eliminarMetricaUsoResponse eliminarMetricaUso(FrontVR.ServiceReference2.eliminarMetricaUsoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/eliminarMetricaUsoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/eliminarMetricaUsoResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.eliminarMetricaUsoResponse> eliminarMetricaUsoAsync(FrontVR.ServiceReference2.eliminarMetricaUsoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerMetricaUsoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerMetricaUsoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference2.Exception), Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerMetricaUso/Fault/Exception" +
            "", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.ServiceReference2.obtenerMetricaUsoResponse obtenerMetricaUso(FrontVR.ServiceReference2.obtenerMetricaUsoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerMetricaUsoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerMetricaUsoResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.obtenerMetricaUsoResponse> obtenerMetricaUsoAsync(FrontVR.ServiceReference2.obtenerMetricaUsoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerDispositivoMenosUsadoReque" +
            "st", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerDispositivoMenosUsadoRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference2.Exception), Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerDispositivoMenosUsado/Faul" +
            "t/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.ServiceReference2.obtenerDispositivoMenosUsadoResponse obtenerDispositivoMenosUsado(FrontVR.ServiceReference2.obtenerDispositivoMenosUsadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerDispositivoMenosUsadoReque" +
            "st", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerDispositivoMenosUsadoRespo" +
            "nse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.obtenerDispositivoMenosUsadoResponse> obtenerDispositivoMenosUsadoAsync(FrontVR.ServiceReference2.obtenerDispositivoMenosUsadoRequest request);
        
        // CODEGEN: El parámetro 'elemento' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/registrarMetricaUsoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/registrarMetricaUsoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference2.Exception), Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/registrarMetricaUso/Fault/Excepti" +
            "on", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.ServiceReference2.registrarMetricaUsoResponse registrarMetricaUso(FrontVR.ServiceReference2.registrarMetricaUsoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/registrarMetricaUsoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/registrarMetricaUsoResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.registrarMetricaUsoResponse> registrarMetricaUsoAsync(FrontVR.ServiceReference2.registrarMetricaUsoRequest request);
        
        // CODEGEN: El parámetro 'elemento' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/actualizarMetricaUsoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/actualizarMetricaUsoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference2.Exception), Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/actualizarMetricaUso/Fault/Except" +
            "ion", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.ServiceReference2.actualizarMetricaUsoResponse actualizarMetricaUso(FrontVR.ServiceReference2.actualizarMetricaUsoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/actualizarMetricaUsoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/actualizarMetricaUsoResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.actualizarMetricaUsoResponse> actualizarMetricaUsoAsync(FrontVR.ServiceReference2.actualizarMetricaUsoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerDispositivoMasUsadoRequest" +
            "", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerDispositivoMasUsadoRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference2.Exception), Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerDispositivoMasUsado/Fault/" +
            "Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.ServiceReference2.obtenerDispositivoMasUsadoResponse obtenerDispositivoMasUsado(FrontVR.ServiceReference2.obtenerDispositivoMasUsadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerDispositivoMasUsadoRequest" +
            "", ReplyAction="http://ws.gestionlentesvr.pucp.com/MetricaUsoWS/obtenerDispositivoMasUsadoRespons" +
            "e")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.obtenerDispositivoMasUsadoResponse> obtenerDispositivoMasUsadoAsync(FrontVR.ServiceReference2.obtenerDispositivoMasUsadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMetricaUso", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class listarMetricaUsoRequest {
        
        public listarMetricaUsoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMetricaUsoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class listarMetricaUsoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference2.metricaUso[] @return;
        
        public listarMetricaUsoResponse() {
        }
        
        public listarMetricaUsoResponse(FrontVR.ServiceReference2.metricaUso[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class aplicacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort activoField;
        
        private categoriaAplicacion categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private string desarrolladorField;
        
        private string descripcionField;
        
        private int idField;
        
        private string nombreField;
        
        private double tamanombField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public categoriaAplicacion categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified {
            get {
                return this.categoriaFieldSpecified;
            }
            set {
                this.categoriaFieldSpecified = value;
                this.RaisePropertyChanged("categoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string desarrollador {
            get {
                return this.desarrolladorField;
            }
            set {
                this.desarrolladorField = value;
                this.RaisePropertyChanged("desarrollador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double tamanomb {
            get {
                return this.tamanombField;
            }
            set {
                this.tamanombField = value;
                this.RaisePropertyChanged("tamanomb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public enum categoriaAplicacion {
        
        /// <remarks/>
        EDUCATIVA,
        
        /// <remarks/>
        ENTRETENIMIENTO,
        
        /// <remarks/>
        TERAPEUTICA,
        
        /// <remarks/>
        ENTRENAMIENTO,
        
        /// <remarks/>
        PRODUCTIVIDAD,
        
        /// <remarks/>
        SIMULACION,
        
        /// <remarks/>
        MULTIMEDIA,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAppMasUsada", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerAppMasUsadaRequest {
        
        public obtenerAppMasUsadaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAppMasUsadaResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerAppMasUsadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference2.aplicacion @return;
        
        public obtenerAppMasUsadaResponse() {
        }
        
        public obtenerAppMasUsadaResponse(FrontVR.ServiceReference2.aplicacion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMetricaUso", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class eliminarMetricaUsoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarMetricaUsoRequest() {
        }
        
        public eliminarMetricaUsoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMetricaUsoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class eliminarMetricaUsoResponse {
        
        public eliminarMetricaUsoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMetricaUso", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerMetricaUsoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerMetricaUsoRequest() {
        }
        
        public obtenerMetricaUsoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMetricaUsoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerMetricaUsoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference2.metricaUso @return;
        
        public obtenerMetricaUsoResponse() {
        }
        
        public obtenerMetricaUsoResponse(FrontVR.ServiceReference2.metricaUso @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDispositivoMenosUsado", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerDispositivoMenosUsadoRequest {
        
        public obtenerDispositivoMenosUsadoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDispositivoMenosUsadoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerDispositivoMenosUsadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference2.dispositivo @return;
        
        public obtenerDispositivoMenosUsadoResponse() {
        }
        
        public obtenerDispositivoMenosUsadoResponse(FrontVR.ServiceReference2.dispositivo @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarMetricaUso", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class registrarMetricaUsoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference2.metricaUso elemento;
        
        public registrarMetricaUsoRequest() {
        }
        
        public registrarMetricaUsoRequest(FrontVR.ServiceReference2.metricaUso elemento) {
            this.elemento = elemento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarMetricaUsoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class registrarMetricaUsoResponse {
        
        public registrarMetricaUsoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarMetricaUso", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class actualizarMetricaUsoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference2.metricaUso elemento;
        
        public actualizarMetricaUsoRequest() {
        }
        
        public actualizarMetricaUsoRequest(FrontVR.ServiceReference2.metricaUso elemento) {
            this.elemento = elemento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarMetricaUsoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class actualizarMetricaUsoResponse {
        
        public actualizarMetricaUsoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDispositivoMasUsado", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerDispositivoMasUsadoRequest {
        
        public obtenerDispositivoMasUsadoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDispositivoMasUsadoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerDispositivoMasUsadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference2.dispositivo @return;
        
        public obtenerDispositivoMasUsadoResponse() {
        }
        
        public obtenerDispositivoMasUsadoResponse(FrontVR.ServiceReference2.dispositivo @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MetricaUsoWSChannel : FrontVR.ServiceReference2.MetricaUsoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MetricaUsoWSClient : System.ServiceModel.ClientBase<FrontVR.ServiceReference2.MetricaUsoWS>, FrontVR.ServiceReference2.MetricaUsoWS {
        
        public MetricaUsoWSClient() {
        }
        
        public MetricaUsoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetricaUsoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetricaUsoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetricaUsoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference2.listarMetricaUsoResponse FrontVR.ServiceReference2.MetricaUsoWS.listarMetricaUso(FrontVR.ServiceReference2.listarMetricaUsoRequest request) {
            return base.Channel.listarMetricaUso(request);
        }
        
        public FrontVR.ServiceReference2.metricaUso[] listarMetricaUso() {
            FrontVR.ServiceReference2.listarMetricaUsoRequest inValue = new FrontVR.ServiceReference2.listarMetricaUsoRequest();
            FrontVR.ServiceReference2.listarMetricaUsoResponse retVal = ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).listarMetricaUso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.listarMetricaUsoResponse> FrontVR.ServiceReference2.MetricaUsoWS.listarMetricaUsoAsync(FrontVR.ServiceReference2.listarMetricaUsoRequest request) {
            return base.Channel.listarMetricaUsoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference2.listarMetricaUsoResponse> listarMetricaUsoAsync() {
            FrontVR.ServiceReference2.listarMetricaUsoRequest inValue = new FrontVR.ServiceReference2.listarMetricaUsoRequest();
            return ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).listarMetricaUsoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference2.obtenerAppMasUsadaResponse FrontVR.ServiceReference2.MetricaUsoWS.obtenerAppMasUsada(FrontVR.ServiceReference2.obtenerAppMasUsadaRequest request) {
            return base.Channel.obtenerAppMasUsada(request);
        }
        
        public FrontVR.ServiceReference2.aplicacion obtenerAppMasUsada() {
            FrontVR.ServiceReference2.obtenerAppMasUsadaRequest inValue = new FrontVR.ServiceReference2.obtenerAppMasUsadaRequest();
            FrontVR.ServiceReference2.obtenerAppMasUsadaResponse retVal = ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).obtenerAppMasUsada(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.obtenerAppMasUsadaResponse> FrontVR.ServiceReference2.MetricaUsoWS.obtenerAppMasUsadaAsync(FrontVR.ServiceReference2.obtenerAppMasUsadaRequest request) {
            return base.Channel.obtenerAppMasUsadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference2.obtenerAppMasUsadaResponse> obtenerAppMasUsadaAsync() {
            FrontVR.ServiceReference2.obtenerAppMasUsadaRequest inValue = new FrontVR.ServiceReference2.obtenerAppMasUsadaRequest();
            return ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).obtenerAppMasUsadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference2.eliminarMetricaUsoResponse FrontVR.ServiceReference2.MetricaUsoWS.eliminarMetricaUso(FrontVR.ServiceReference2.eliminarMetricaUsoRequest request) {
            return base.Channel.eliminarMetricaUso(request);
        }
        
        public void eliminarMetricaUso(int id) {
            FrontVR.ServiceReference2.eliminarMetricaUsoRequest inValue = new FrontVR.ServiceReference2.eliminarMetricaUsoRequest();
            inValue.id = id;
            FrontVR.ServiceReference2.eliminarMetricaUsoResponse retVal = ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).eliminarMetricaUso(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.eliminarMetricaUsoResponse> FrontVR.ServiceReference2.MetricaUsoWS.eliminarMetricaUsoAsync(FrontVR.ServiceReference2.eliminarMetricaUsoRequest request) {
            return base.Channel.eliminarMetricaUsoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference2.eliminarMetricaUsoResponse> eliminarMetricaUsoAsync(int id) {
            FrontVR.ServiceReference2.eliminarMetricaUsoRequest inValue = new FrontVR.ServiceReference2.eliminarMetricaUsoRequest();
            inValue.id = id;
            return ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).eliminarMetricaUsoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference2.obtenerMetricaUsoResponse FrontVR.ServiceReference2.MetricaUsoWS.obtenerMetricaUso(FrontVR.ServiceReference2.obtenerMetricaUsoRequest request) {
            return base.Channel.obtenerMetricaUso(request);
        }
        
        public FrontVR.ServiceReference2.metricaUso obtenerMetricaUso(int id) {
            FrontVR.ServiceReference2.obtenerMetricaUsoRequest inValue = new FrontVR.ServiceReference2.obtenerMetricaUsoRequest();
            inValue.id = id;
            FrontVR.ServiceReference2.obtenerMetricaUsoResponse retVal = ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).obtenerMetricaUso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.obtenerMetricaUsoResponse> FrontVR.ServiceReference2.MetricaUsoWS.obtenerMetricaUsoAsync(FrontVR.ServiceReference2.obtenerMetricaUsoRequest request) {
            return base.Channel.obtenerMetricaUsoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference2.obtenerMetricaUsoResponse> obtenerMetricaUsoAsync(int id) {
            FrontVR.ServiceReference2.obtenerMetricaUsoRequest inValue = new FrontVR.ServiceReference2.obtenerMetricaUsoRequest();
            inValue.id = id;
            return ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).obtenerMetricaUsoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference2.obtenerDispositivoMenosUsadoResponse FrontVR.ServiceReference2.MetricaUsoWS.obtenerDispositivoMenosUsado(FrontVR.ServiceReference2.obtenerDispositivoMenosUsadoRequest request) {
            return base.Channel.obtenerDispositivoMenosUsado(request);
        }
        
        public FrontVR.ServiceReference2.dispositivo obtenerDispositivoMenosUsado() {
            FrontVR.ServiceReference2.obtenerDispositivoMenosUsadoRequest inValue = new FrontVR.ServiceReference2.obtenerDispositivoMenosUsadoRequest();
            FrontVR.ServiceReference2.obtenerDispositivoMenosUsadoResponse retVal = ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).obtenerDispositivoMenosUsado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.obtenerDispositivoMenosUsadoResponse> FrontVR.ServiceReference2.MetricaUsoWS.obtenerDispositivoMenosUsadoAsync(FrontVR.ServiceReference2.obtenerDispositivoMenosUsadoRequest request) {
            return base.Channel.obtenerDispositivoMenosUsadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference2.obtenerDispositivoMenosUsadoResponse> obtenerDispositivoMenosUsadoAsync() {
            FrontVR.ServiceReference2.obtenerDispositivoMenosUsadoRequest inValue = new FrontVR.ServiceReference2.obtenerDispositivoMenosUsadoRequest();
            return ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).obtenerDispositivoMenosUsadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference2.registrarMetricaUsoResponse FrontVR.ServiceReference2.MetricaUsoWS.registrarMetricaUso(FrontVR.ServiceReference2.registrarMetricaUsoRequest request) {
            return base.Channel.registrarMetricaUso(request);
        }
        
        public void registrarMetricaUso(FrontVR.ServiceReference2.metricaUso elemento) {
            FrontVR.ServiceReference2.registrarMetricaUsoRequest inValue = new FrontVR.ServiceReference2.registrarMetricaUsoRequest();
            inValue.elemento = elemento;
            FrontVR.ServiceReference2.registrarMetricaUsoResponse retVal = ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).registrarMetricaUso(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.registrarMetricaUsoResponse> FrontVR.ServiceReference2.MetricaUsoWS.registrarMetricaUsoAsync(FrontVR.ServiceReference2.registrarMetricaUsoRequest request) {
            return base.Channel.registrarMetricaUsoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference2.registrarMetricaUsoResponse> registrarMetricaUsoAsync(FrontVR.ServiceReference2.metricaUso elemento) {
            FrontVR.ServiceReference2.registrarMetricaUsoRequest inValue = new FrontVR.ServiceReference2.registrarMetricaUsoRequest();
            inValue.elemento = elemento;
            return ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).registrarMetricaUsoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference2.actualizarMetricaUsoResponse FrontVR.ServiceReference2.MetricaUsoWS.actualizarMetricaUso(FrontVR.ServiceReference2.actualizarMetricaUsoRequest request) {
            return base.Channel.actualizarMetricaUso(request);
        }
        
        public void actualizarMetricaUso(FrontVR.ServiceReference2.metricaUso elemento) {
            FrontVR.ServiceReference2.actualizarMetricaUsoRequest inValue = new FrontVR.ServiceReference2.actualizarMetricaUsoRequest();
            inValue.elemento = elemento;
            FrontVR.ServiceReference2.actualizarMetricaUsoResponse retVal = ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).actualizarMetricaUso(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.actualizarMetricaUsoResponse> FrontVR.ServiceReference2.MetricaUsoWS.actualizarMetricaUsoAsync(FrontVR.ServiceReference2.actualizarMetricaUsoRequest request) {
            return base.Channel.actualizarMetricaUsoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference2.actualizarMetricaUsoResponse> actualizarMetricaUsoAsync(FrontVR.ServiceReference2.metricaUso elemento) {
            FrontVR.ServiceReference2.actualizarMetricaUsoRequest inValue = new FrontVR.ServiceReference2.actualizarMetricaUsoRequest();
            inValue.elemento = elemento;
            return ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).actualizarMetricaUsoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference2.obtenerDispositivoMasUsadoResponse FrontVR.ServiceReference2.MetricaUsoWS.obtenerDispositivoMasUsado(FrontVR.ServiceReference2.obtenerDispositivoMasUsadoRequest request) {
            return base.Channel.obtenerDispositivoMasUsado(request);
        }
        
        public FrontVR.ServiceReference2.dispositivo obtenerDispositivoMasUsado() {
            FrontVR.ServiceReference2.obtenerDispositivoMasUsadoRequest inValue = new FrontVR.ServiceReference2.obtenerDispositivoMasUsadoRequest();
            FrontVR.ServiceReference2.obtenerDispositivoMasUsadoResponse retVal = ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).obtenerDispositivoMasUsado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference2.obtenerDispositivoMasUsadoResponse> FrontVR.ServiceReference2.MetricaUsoWS.obtenerDispositivoMasUsadoAsync(FrontVR.ServiceReference2.obtenerDispositivoMasUsadoRequest request) {
            return base.Channel.obtenerDispositivoMasUsadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference2.obtenerDispositivoMasUsadoResponse> obtenerDispositivoMasUsadoAsync() {
            FrontVR.ServiceReference2.obtenerDispositivoMasUsadoRequest inValue = new FrontVR.ServiceReference2.obtenerDispositivoMasUsadoRequest();
            return ((FrontVR.ServiceReference2.MetricaUsoWS)(this)).obtenerDispositivoMasUsadoAsync(inValue);
        }
    }
}
