//------------------------------------------------------------------------------
<<<<<<< HEAD
// <generado automáticamente>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código. 
// </generado automáticamente>
=======
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
>>>>>>> 72e72ce (Ignorar archivos temporales de Visual Studio y build)
//------------------------------------------------------------------------------

namespace FrontVR.Vistas
{


    public partial class Grupos
    {

        /// <summary>
<<<<<<< HEAD
        /// Control gvGrupos.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
=======
        /// gvGrupos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
>>>>>>> 72e72ce (Ignorar archivos temporales de Visual Studio y build)
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvGrupos;

        /// <summary>
<<<<<<< HEAD
        /// Control upModalGrupo.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
=======
        /// upModalGrupo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
>>>>>>> 72e72ce (Ignorar archivos temporales de Visual Studio y build)
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upModalGrupo;

        /// <summary>
<<<<<<< HEAD
        /// Control hfIdGrupo.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
=======
        /// hfIdGrupo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
>>>>>>> 72e72ce (Ignorar archivos temporales de Visual Studio y build)
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfIdGrupo;

        /// <summary>
<<<<<<< HEAD
        /// Control txtNombreGrupo.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
=======
        /// txtNombreGrupo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
>>>>>>> 72e72ce (Ignorar archivos temporales de Visual Studio y build)
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNombreGrupo;

        /// <summary>
<<<<<<< HEAD
        /// Control txtDescripcionGrupo.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
=======
        /// txtDescripcionGrupo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
>>>>>>> 72e72ce (Ignorar archivos temporales de Visual Studio y build)
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDescripcionGrupo;

        /// <summary>
<<<<<<< HEAD
        /// Control txtUbicacionGrupo.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
=======
        /// txtUbicacionGrupo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
>>>>>>> 72e72ce (Ignorar archivos temporales de Visual Studio y build)
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtUbicacionGrupo;

        /// <summary>
<<<<<<< HEAD
        /// Control lblErrorGrupo.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
=======
        /// lblErrorGrupo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
>>>>>>> 72e72ce (Ignorar archivos temporales de Visual Studio y build)
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblErrorGrupo;

        /// <summary>
<<<<<<< HEAD
        /// Control btnGuardarGrupo.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
=======
        /// btnGuardarGrupo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
>>>>>>> 72e72ce (Ignorar archivos temporales de Visual Studio y build)
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnGuardarGrupo;
    }
}
