//------------------------------------------------------------------------------
<<<<<<< HEAD
// <generado automáticamente>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código. 
// </generado automáticamente>
=======
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
>>>>>>> 72e72ce (Ignorar archivos temporales de Visual Studio y build)
//------------------------------------------------------------------------------

namespace FrontVR.Vistas
{


    public partial class Metricas
    {
<<<<<<< HEAD
=======

        /// <summary>
        /// lblMasUsadoData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMasUsadoData;

        /// <summary>
        /// lblMenosUsadoData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMenosUsadoData;

        /// <summary>
        /// lblAppPopularData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblAppPopularData;
>>>>>>> 72e72ce (Ignorar archivos temporales de Visual Studio y build)
    }
}
