//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontVR.ServiceReference3 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class grupo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort activoField;
        
        private string descripcionField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private int idField;
        
        private string nombreField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public partial class dispositivo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort activoField;
        
        private estadoConexion estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private grupo grupoField;
        
        private int idField;
        
        private string modeloField;
        
        private int nivelBateriaField;
        
        private string nombreField;
        
        private string numeroSerieField;
        
        private string ubicacionField;
        
        private System.DateTime ultimaConexionField;
        
        private bool ultimaConexionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoConexion estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public grupo grupo {
            get {
                return this.grupoField;
            }
            set {
                this.grupoField = value;
                this.RaisePropertyChanged("grupo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int nivelBateria {
            get {
                return this.nivelBateriaField;
            }
            set {
                this.nivelBateriaField = value;
                this.RaisePropertyChanged("nivelBateria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string numeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                this.numeroSerieField = value;
                this.RaisePropertyChanged("numeroSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime ultimaConexion {
            get {
                return this.ultimaConexionField;
            }
            set {
                this.ultimaConexionField = value;
                this.RaisePropertyChanged("ultimaConexion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ultimaConexionSpecified {
            get {
                return this.ultimaConexionFieldSpecified;
            }
            set {
                this.ultimaConexionFieldSpecified = value;
                this.RaisePropertyChanged("ultimaConexionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/")]
    public enum estadoConexion {
        
        /// <remarks/>
        CONECTADO,
        
        /// <remarks/>
        DESCONECTADO,
        
        /// <remarks/>
        EN_USO,
        
        /// <remarks/>
        EN_MANTENIMIENTO,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", ConfigurationName="ServiceReference3.DispositivoWS")]
    public interface DispositivoWS {
        
        // CODEGEN: El parámetro 'elemento' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/actualizarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/actualizarDispositivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference3.Exception), Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/actualizarDispositivo/Fault/Exce" +
            "ption", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.ServiceReference3.actualizarDispositivoResponse actualizarDispositivo(FrontVR.ServiceReference3.actualizarDispositivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/actualizarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/actualizarDispositivoResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference3.actualizarDispositivoResponse> actualizarDispositivoAsync(FrontVR.ServiceReference3.actualizarDispositivoRequest request);
        
        // CODEGEN: El parámetro 'id' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/eliminarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/eliminarDispositivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference3.Exception), Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/eliminarDispositivo/Fault/Except" +
            "ion", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.ServiceReference3.eliminarDispositivoResponse eliminarDispositivo(FrontVR.ServiceReference3.eliminarDispositivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/eliminarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/eliminarDispositivoResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference3.eliminarDispositivoResponse> eliminarDispositivoAsync(FrontVR.ServiceReference3.eliminarDispositivoRequest request);
        
        // CODEGEN: El parámetro 'elemento' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/registrarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/registrarDispositivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference3.Exception), Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/registrarDispositivo/Fault/Excep" +
            "tion", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontVR.ServiceReference3.registrarDispositivoResponse registrarDispositivo(FrontVR.ServiceReference3.registrarDispositivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/registrarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/registrarDispositivoResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference3.registrarDispositivoResponse> registrarDispositivoAsync(FrontVR.ServiceReference3.registrarDispositivoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/obtenerDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/obtenerDispositivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference3.Exception), Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/obtenerDispositivo/Fault/Excepti" +
            "on", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.ServiceReference3.obtenerDispositivoResponse obtenerDispositivo(FrontVR.ServiceReference3.obtenerDispositivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/obtenerDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/obtenerDispositivoResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference3.obtenerDispositivoResponse> obtenerDispositivoAsync(FrontVR.ServiceReference3.obtenerDispositivoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/listarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/listarDispositivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FrontVR.ServiceReference3.Exception), Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/listarDispositivo/Fault/Exceptio" +
            "n", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontVR.ServiceReference3.listarDispositivoResponse listarDispositivo(FrontVR.ServiceReference3.listarDispositivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gestionlentesvr.pucp.com/DispositivoWS/listarDispositivoRequest", ReplyAction="http://ws.gestionlentesvr.pucp.com/DispositivoWS/listarDispositivoResponse")]
        System.Threading.Tasks.Task<FrontVR.ServiceReference3.listarDispositivoResponse> listarDispositivoAsync(FrontVR.ServiceReference3.listarDispositivoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarDispositivo", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class actualizarDispositivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference3.dispositivo elemento;
        
        public actualizarDispositivoRequest() {
        }
        
        public actualizarDispositivoRequest(FrontVR.ServiceReference3.dispositivo elemento) {
            this.elemento = elemento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarDispositivoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class actualizarDispositivoResponse {
        
        public actualizarDispositivoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDispositivo", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class eliminarDispositivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarDispositivoRequest() {
        }
        
        public eliminarDispositivoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDispositivoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class eliminarDispositivoResponse {
        
        public eliminarDispositivoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarDispositivo", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class registrarDispositivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference3.dispositivo elemento;
        
        public registrarDispositivoRequest() {
        }
        
        public registrarDispositivoRequest(FrontVR.ServiceReference3.dispositivo elemento) {
            this.elemento = elemento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarDispositivoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class registrarDispositivoResponse {
        
        public registrarDispositivoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDispositivo", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerDispositivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerDispositivoRequest() {
        }
        
        public obtenerDispositivoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDispositivoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class obtenerDispositivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference3.dispositivo @return;
        
        public obtenerDispositivoResponse() {
        }
        
        public obtenerDispositivoResponse(FrontVR.ServiceReference3.dispositivo @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDispositivo", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class listarDispositivoRequest {
        
        public listarDispositivoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDispositivoResponse", WrapperNamespace="http://ws.gestionlentesvr.pucp.com/", IsWrapped=true)]
    public partial class listarDispositivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionlentesvr.pucp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontVR.ServiceReference3.dispositivo[] @return;
        
        public listarDispositivoResponse() {
        }
        
        public listarDispositivoResponse(FrontVR.ServiceReference3.dispositivo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DispositivoWSChannel : FrontVR.ServiceReference3.DispositivoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DispositivoWSClient : System.ServiceModel.ClientBase<FrontVR.ServiceReference3.DispositivoWS>, FrontVR.ServiceReference3.DispositivoWS {
        
        public DispositivoWSClient() {
        }
        
        public DispositivoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DispositivoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DispositivoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DispositivoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference3.actualizarDispositivoResponse FrontVR.ServiceReference3.DispositivoWS.actualizarDispositivo(FrontVR.ServiceReference3.actualizarDispositivoRequest request) {
            return base.Channel.actualizarDispositivo(request);
        }
        
        public void actualizarDispositivo(FrontVR.ServiceReference3.dispositivo elemento) {
            FrontVR.ServiceReference3.actualizarDispositivoRequest inValue = new FrontVR.ServiceReference3.actualizarDispositivoRequest();
            inValue.elemento = elemento;
            FrontVR.ServiceReference3.actualizarDispositivoResponse retVal = ((FrontVR.ServiceReference3.DispositivoWS)(this)).actualizarDispositivo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference3.actualizarDispositivoResponse> FrontVR.ServiceReference3.DispositivoWS.actualizarDispositivoAsync(FrontVR.ServiceReference3.actualizarDispositivoRequest request) {
            return base.Channel.actualizarDispositivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference3.actualizarDispositivoResponse> actualizarDispositivoAsync(FrontVR.ServiceReference3.dispositivo elemento) {
            FrontVR.ServiceReference3.actualizarDispositivoRequest inValue = new FrontVR.ServiceReference3.actualizarDispositivoRequest();
            inValue.elemento = elemento;
            return ((FrontVR.ServiceReference3.DispositivoWS)(this)).actualizarDispositivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference3.eliminarDispositivoResponse FrontVR.ServiceReference3.DispositivoWS.eliminarDispositivo(FrontVR.ServiceReference3.eliminarDispositivoRequest request) {
            return base.Channel.eliminarDispositivo(request);
        }
        
        public void eliminarDispositivo(int id) {
            FrontVR.ServiceReference3.eliminarDispositivoRequest inValue = new FrontVR.ServiceReference3.eliminarDispositivoRequest();
            inValue.id = id;
            FrontVR.ServiceReference3.eliminarDispositivoResponse retVal = ((FrontVR.ServiceReference3.DispositivoWS)(this)).eliminarDispositivo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference3.eliminarDispositivoResponse> FrontVR.ServiceReference3.DispositivoWS.eliminarDispositivoAsync(FrontVR.ServiceReference3.eliminarDispositivoRequest request) {
            return base.Channel.eliminarDispositivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference3.eliminarDispositivoResponse> eliminarDispositivoAsync(int id) {
            FrontVR.ServiceReference3.eliminarDispositivoRequest inValue = new FrontVR.ServiceReference3.eliminarDispositivoRequest();
            inValue.id = id;
            return ((FrontVR.ServiceReference3.DispositivoWS)(this)).eliminarDispositivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference3.registrarDispositivoResponse FrontVR.ServiceReference3.DispositivoWS.registrarDispositivo(FrontVR.ServiceReference3.registrarDispositivoRequest request) {
            return base.Channel.registrarDispositivo(request);
        }
        
        public void registrarDispositivo(FrontVR.ServiceReference3.dispositivo elemento) {
            FrontVR.ServiceReference3.registrarDispositivoRequest inValue = new FrontVR.ServiceReference3.registrarDispositivoRequest();
            inValue.elemento = elemento;
            FrontVR.ServiceReference3.registrarDispositivoResponse retVal = ((FrontVR.ServiceReference3.DispositivoWS)(this)).registrarDispositivo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference3.registrarDispositivoResponse> FrontVR.ServiceReference3.DispositivoWS.registrarDispositivoAsync(FrontVR.ServiceReference3.registrarDispositivoRequest request) {
            return base.Channel.registrarDispositivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference3.registrarDispositivoResponse> registrarDispositivoAsync(FrontVR.ServiceReference3.dispositivo elemento) {
            FrontVR.ServiceReference3.registrarDispositivoRequest inValue = new FrontVR.ServiceReference3.registrarDispositivoRequest();
            inValue.elemento = elemento;
            return ((FrontVR.ServiceReference3.DispositivoWS)(this)).registrarDispositivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference3.obtenerDispositivoResponse FrontVR.ServiceReference3.DispositivoWS.obtenerDispositivo(FrontVR.ServiceReference3.obtenerDispositivoRequest request) {
            return base.Channel.obtenerDispositivo(request);
        }
        
        public FrontVR.ServiceReference3.dispositivo obtenerDispositivo(int id) {
            FrontVR.ServiceReference3.obtenerDispositivoRequest inValue = new FrontVR.ServiceReference3.obtenerDispositivoRequest();
            inValue.id = id;
            FrontVR.ServiceReference3.obtenerDispositivoResponse retVal = ((FrontVR.ServiceReference3.DispositivoWS)(this)).obtenerDispositivo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference3.obtenerDispositivoResponse> FrontVR.ServiceReference3.DispositivoWS.obtenerDispositivoAsync(FrontVR.ServiceReference3.obtenerDispositivoRequest request) {
            return base.Channel.obtenerDispositivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference3.obtenerDispositivoResponse> obtenerDispositivoAsync(int id) {
            FrontVR.ServiceReference3.obtenerDispositivoRequest inValue = new FrontVR.ServiceReference3.obtenerDispositivoRequest();
            inValue.id = id;
            return ((FrontVR.ServiceReference3.DispositivoWS)(this)).obtenerDispositivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontVR.ServiceReference3.listarDispositivoResponse FrontVR.ServiceReference3.DispositivoWS.listarDispositivo(FrontVR.ServiceReference3.listarDispositivoRequest request) {
            return base.Channel.listarDispositivo(request);
        }
        
        public FrontVR.ServiceReference3.dispositivo[] listarDispositivo() {
            FrontVR.ServiceReference3.listarDispositivoRequest inValue = new FrontVR.ServiceReference3.listarDispositivoRequest();
            FrontVR.ServiceReference3.listarDispositivoResponse retVal = ((FrontVR.ServiceReference3.DispositivoWS)(this)).listarDispositivo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontVR.ServiceReference3.listarDispositivoResponse> FrontVR.ServiceReference3.DispositivoWS.listarDispositivoAsync(FrontVR.ServiceReference3.listarDispositivoRequest request) {
            return base.Channel.listarDispositivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontVR.ServiceReference3.listarDispositivoResponse> listarDispositivoAsync() {
            FrontVR.ServiceReference3.listarDispositivoRequest inValue = new FrontVR.ServiceReference3.listarDispositivoRequest();
            return ((FrontVR.ServiceReference3.DispositivoWS)(this)).listarDispositivoAsync(inValue);
        }
    }
}
